[package]
name = "db-sql"
version.workspace = true
edition.workspace = true

[dependencies]
bench-core.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["time", "sync"] }
